# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: KeeperSecurity.Commander
PackageVersion: 18.1.7
InstallerLocale: en-US
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- keeper
ProductCode: '{006266E3-17D6-4166-918C-0B8F4C663D4C}_is1'
ReleaseDate: 2026-10-07
AppsAndFeaturesEntries:
- DisplayName: Keeper Commander 18.1.7
  ProductCode: '{006266E3-17D6-4166-918C-0B8F4C663D4C}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Keeper Commander'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/Keeper-Security/Commander/releases/download/v18.1.7/keeper-commander-windows-v18.1.7.exe
  InstallerSha256: E068B38B9F10C6A4AF455528E05981E9A031F7CB4D8C3AFFC28B2C01D8D49E6A
ManifestType: installer
ManifestVersion: 1.12.0
